export const SET_VIDEOS = "RESULT_DATA/SET_VIDEOS";

export const SET_SEARCH_DATA = "RESULT_DATA/SET_SEARCH_DATA";

export const SET_DATA = "RESULT_DATA/SET_DATA";
export const SET_DATA_LOADING = "RESULT_DATA/SET_DATA_LOADING";
export const SET_DATA_ERROR = "RESULT_DATA/SET_DATA_ERROR";